# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17siGZQSZWHkLDOyMHddnLUHOgeWQUlEU
"""

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

df = pd.read_csv("yield_df.csv")

if "Unnamed: 0" in df.columns:
    df = df.drop("Unnamed: 0", axis=1)

print("Dataset Shape:", df.shape)
print("\nMissing Values:\n", df.isnull().sum())
print("\nColumns:\n", df.columns)

df.info()
df.head()
df.describe()
# -----------------------------------------
# 📊 EXPLORATORY DATA ANALYSIS (EDA)
# -----------------------------------------

print("\n===== EDA STARTED =====\n")

# 1. Dataset Overview
print("Shape of dataset:", df.shape)
print("\nColumns:", df.columns.tolist())

# 2. Missing Values Heatmap
plt.figure(figsize=(8,5))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title("Missing Values Heatmap")
plt.show()

# 3. Distribution of Target Variable
plt.figure(figsize=(6,4))
sns.histplot(df['hg/ha_yield'], kde=True)
plt.title("Distribution of Crop Yield")
plt.xlabel("Yield (hg/ha)")
plt.show()

# 4. Correlation Matrix
plt.figure(figsize=(10,6))
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Feature Correlation Matrix")
plt.show()

# 5. Top Crop Producing Areas
top_areas = df.groupby('Area')['hg/ha_yield'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
top_areas.plot(kind='bar')
plt.title("Top 10 Areas by Average Yield")
plt.ylabel("Average Yield")
plt.xticks(rotation=45)
plt.show()

# 6. Top Crops by Yield
top_crops = df.groupby('Item')['hg/ha_yield'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
top_crops.plot(kind='bar', color='green')
plt.title("Top 10 Crops by Average Yield")
plt.ylabel("Average Yield")
plt.xticks(rotation=45)
plt.show()

# 7. Rainfall vs Yield
plt.figure(figsize=(6,4))
sns.scatterplot(x=df['average_rain_fall_mm_per_year'], y=df['hg/ha_yield'])
plt.title("Rainfall vs Yield")
plt.xlabel("Rainfall")
plt.ylabel("Yield")
plt.show()

# 8. Temperature vs Yield
plt.figure(figsize=(6,4))
sns.scatterplot(x=df['avg_temp'], y=df['hg/ha_yield'], color='red')
plt.title("Temperature vs Yield")
plt.xlabel("Temperature")
plt.ylabel("Yield")
plt.show()

print("\n===== EDA COMPLETED =====\n")
# Year vs Yield Trend
year_trend = df.groupby('Year')['hg/ha_yield'].mean()

plt.figure(figsize=(8,5))
year_trend.plot()
plt.title("Year-wise Average Yield Trend")
plt.xlabel("Year")
plt.ylabel("Yield")
plt.grid()
plt.show()
top_countries = df.groupby('Area')['hg/ha_yield'].mean().sort_values(ascending=False).head(15)

plt.figure(figsize=(10,5))
sns.barplot(x=top_countries.values, y=top_countries.index)
plt.title("Top 15 Countries by Yield")
plt.xlabel("Yield")
plt.ylabel("Country")
plt.show()
le_area = LabelEncoder()
le_item = LabelEncoder()

df['Area'] = le_area.fit_transform(df['Area'])
df['Item'] = le_item.fit_transform(df['Item'])
X = df.drop('hg/ha_yield', axis=1)
y = df['hg/ha_yield']

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42
)
models = {
    "SVR":            SVR(kernel='rbf', C=100, epsilon=0.1),      # ✅ Paper's best model
    "KNN Regressor":  KNeighborsRegressor(n_neighbors=5),          # ✅ Added
    "XGBoost":        XGBRegressor(n_estimators=200,
                                    random_state=42,
                                    verbosity=0),                   # ✅ Added
    "Random Forest":  RandomForestRegressor(n_estimators=200,
                                             random_state=42),
    "Decision Tree":  DecisionTreeRegressor(random_state=42)
}

results = {}
trained_models = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    results[name] = {
        "R2 Score": round(r2, 4),
        "MAE": round(mae, 2),
        "RMSE": round(rmse, 2)
    }

    trained_models[name] = model

results_df = pd.DataFrame(results).T.sort_values(by="R2 Score", ascending=False)

print("\n📊 Model Comparison:\n")
print(results_df)

best_model_name = results_df.index[0]
model = trained_models[best_model_name]

print(f"\n🏆 Best Model Selected: {best_model_name}")
rf_model = RandomForestRegressor(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

importances = rf_model.feature_importances_
feature_names = X.columns

feat_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x='Importance', y='Feature', data=feat_df)
plt.title("Feature Importance")
plt.show()
results = {}
trained_models = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    r2   = r2_score(y_test, y_pred)
    mae  = mean_absolute_error(y_test, y_pred)
    mse  = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    std  = np.std(y_test - y_pred)       # ✅ Added STD

    results[name] = {
        "R2 Score":  round(r2, 4),
        "MAE":       round(mae, 2),
        "MSE":       round(mse, 2),
        "RMSE":      round(rmse, 4),
        "Std Dev":   round(std, 2)        # ✅ Added
    }
    trained_models[name] = model

results_df = pd.DataFrame(results).T.sort_values(
                by="R2 Score", ascending=False)
print("\n📊 Model Comparison:\n")
print(results_df)
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Apply MICE on numeric columns only
numeric_cols = df.select_dtypes(include=[np.number]).columns

mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df[numeric_cols] = mice_imputer.fit_transform(df[numeric_cols])

print("✅ MICE Imputation completed. Missing values after:")
print(df.isnull().sum())
print("\nAvailable Areas:\n", le_area.classes_)
print("\nAvailable Crops:\n", le_item.classes_)

def predict_yield(Area, Item, Year,
                  average_rain_fall_mm_per_year,
                  pesticides_tonnes,
                  avg_temp):

    # Remove extra spaces
    Area = Area.strip()
    Item = Item.strip()

    # Case-insensitive matching
    area_dict = {a.lower(): a for a in le_area.classes_}
    item_dict = {i.lower(): i for i in le_item.classes_}

    if Area.lower() not in area_dict:
        raise ValueError("❌ Area not found in dataset.")

    if Item.lower() not in item_dict:
        raise ValueError("❌ Item not found in dataset.")

    Area_corrected = area_dict[Area.lower()]
    Item_corrected = item_dict[Item.lower()]

    # Encode
    area_encoded = le_area.transform([Area_corrected])[0]
    item_encoded = le_item.transform([Item_corrected])[0]

    # Create input DataFrame
    input_df = pd.DataFrame({
        "Area": [area_encoded],
        "Item": [item_encoded],
        "Year": [Year],
        "average_rain_fall_mm_per_year": [average_rain_fall_mm_per_year],
        "pesticides_tonnes": [pesticides_tonnes],
        "avg_temp": [avg_temp]
    })

    # Match training feature order
    input_df = input_df[X.columns]

    # Scale
    input_scaled = scaler.transform(input_df)

    # Predict
    prediction = model.predict(input_scaled)

    return prediction[0]

print("\nEnter Details for Yield Prediction :")

Area = input("Area: ")
Item = input("Item (Crop): ")
Year = int(input("Year (e.g., 2027): "))
average_rain_fall_mm_per_year = float(input("Average Rainfall (mm per year): "))
pesticides_tonnes = float(input("Pesticides (tonnes): "))
avg_temp = float(input("Average Temperature: "))

predicted_yield = predict_yield(
    Area=Area,
    Item=Item,
    Year=Year,
    average_rain_fall_mm_per_year=average_rain_fall_mm_per_year,
    pesticides_tonnes=pesticides_tonnes,
    avg_temp=avg_temp
)

print("\n🌾 Predicted Yield (hg/ha):", round(predicted_yield, 2))